export default {
  DOCKET_CREATION_SUCCEEDED: 'DOCKET_CREATION_SUCCEEDED',
  DOCKET_CREATION_FAILED: 'DOCKET_CREATION_FAILED',
  BALLOT_CREATION_SUCCEEDED: 'BALLOT_CREATION_SUCCEEDED',
  BALLOT_CREATION_FAILED: 'BALLOT_CREATION_FAILED',
  DOCKET_FETCH_SUCCEEDED: 'DOCKET_FETCH_SUCCEEDED',
  DOCKET_FETCH_FAILED: 'DOCKET_FETCH_FAILED',
  UPDATE_TITLE: 'UPDATE_TITLE',
  ADD_MEMBER: 'ADD_MEMBER',
  FINALIZE_DOCKET: 'FINALIZE_DOCKET',
  FETCH_DOCKET: 'FETCH_DOCKET',
  MOVE_CARD: 'MOVE_CARD',
  DELETE_CARD: 'DELETE_CARD',
  CREATE_BALLOT: 'CREATE_BALLOT'
};